/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/theme.ts
 * Command: astryx theme build src/theme/theme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./app.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const icons: IconRegistry;
export declare const appTheme: DefinedTheme;
