import type { IconRegistry } from '@astryxdesign/core/Icon';
import {
  ArrowDownIcon,
  ArrowSquareOutIcon,
  ArrowsDownUpIcon,
  ArrowUpIcon,
  CalendarIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChecksIcon,
  ClockIcon,
  ColumnsIcon,
  CopyIcon,
  DotsThreeIcon,
  EyeSlashIcon,
  FunnelIcon,
  InfoIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  StopIcon,
  WarningIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon,
} from '@phosphor-icons/react';
import { createElement } from 'react';

export const icons = {
  close: createElement(XIcon),
  chevronDown: createElement(CaretDownIcon),
  chevronLeft: createElement(CaretLeftIcon),
  chevronRight: createElement(CaretRightIcon),
  chevronsLeft: createElement(CaretDoubleLeftIcon),
  chevronsRight: createElement(CaretDoubleRightIcon),
  check: createElement(CheckIcon),
  success: createElement(CheckCircleIcon),
  error: createElement(XCircleIcon),
  warning: createElement(WarningIcon),
  info: createElement(InfoIcon),
  calendar: createElement(CalendarIcon),
  clock: createElement(ClockIcon),
  externalLink: createElement(ArrowSquareOutIcon),
  menu: createElement(ListIcon),
  moreHorizontal: createElement(DotsThreeIcon),
  search: createElement(MagnifyingGlassIcon),
  arrowUp: createElement(ArrowUpIcon),
  arrowDown: createElement(ArrowDownIcon),
  arrowsUpDown: createElement(ArrowsDownUpIcon),
  funnel: createElement(FunnelIcon),
  eyeSlash: createElement(EyeSlashIcon),
  viewColumns: createElement(ColumnsIcon),
  copy: createElement(CopyIcon),
  checkDouble: createElement(ChecksIcon),
  wrench: createElement(WrenchIcon),
  stop: createElement(StopIcon),
  microphone: createElement(MicrophoneIcon),
} satisfies IconRegistry;
