packages:
  - apps/*
  - packages/*
  - tools/*

cargo:
  enabled: true

catalogMode: prefer

catalog:
  '@astryxdesign/build': 0.6.2
  '@astryxdesign/cli': 0.6.2
  '@astryxdesign/core': 0.6.2
  '@astryxdesign/theme-neutral': 0.6.2
  '@babel/core': 8.0.1
  '@base-ui/react': 1.8.0
  '@base-ui/utils': 0.4.0
  '@phosphor-icons/react': 2.1.10
  '@oxlint/plugins': 1.82.0
  '@stylexjs/babel-plugin': 0.19.0
  '@stylexjs/stylex': 0.19.0
  '@stylexjs/unplugin': 0.19.0
  '@tanstack/react-router': 1.170.34
  '@tanstack/react-start': 1.168.51
  '@tanstack/router-cli': 1.167.35
  '@types/node': 26.5.1
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  '@vitejs/plugin-react': 6.1.1
  oxc-transform-react: 0.149.0
  oxlint: 1.82.0
  react: 19.3.0
  react-dom: 19.3.0
  typescript: 7.0.2
  unplugin: 3.3.0
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
  vitest: 4.1.11
  vitest-browser-react: 2.3.0
overrides:
  vite: 'catalog:'
  '@types/node': 'catalog:'
  typescript: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
allowBuilds:
  '@astryxdesign/cli': true
  '@astryxdesign/core': true
  cpu-features: set this to true or false
  esbuild: true
  lightningcss: true
  protobufjs: set this to true or false
  ssh2: set this to true or false
minimumReleaseAgeExclude:
  - '@types/node@26.4.0'
